{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactive",
    "version": "1.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.7.3.jar",
          "url": "kotlinx-coroutines-reactive-1.7.3.jar",
          "size": 70943,
          "sha512": "e3e70c81bb2157d2fa4eafac8aa078b87966bbbaac30f7e29065fac0f4d91ca3cf2e5d99a51065fa30a0be558d9883a34c3c85b550c37f70e9cc41bd3887acd0",
          "sha256": "dc6d2add2e9a2d6574bc6f4e80ed0d397e6ca5c27196dfc6ab82322d712d71be",
          "sha1": "3f30c8dd5cd0993ca2804591210141be762786f8",
          "md5": "b6c8a6673993cb06f9409946e5491444"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.7.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.7.3.jar",
          "url": "kotlinx-coroutines-reactive-1.7.3.jar",
          "size": 70943,
          "sha512": "e3e70c81bb2157d2fa4eafac8aa078b87966bbbaac30f7e29065fac0f4d91ca3cf2e5d99a51065fa30a0be558d9883a34c3c85b550c37f70e9cc41bd3887acd0",
          "sha256": "dc6d2add2e9a2d6574bc6f4e80ed0d397e6ca5c27196dfc6ab82322d712d71be",
          "sha1": "3f30c8dd5cd0993ca2804591210141be762786f8",
          "md5": "b6c8a6673993cb06f9409946e5491444"
        }
      ]
    }
  ]
}
