{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.browser",
    "module": "browser",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6975608"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.3.0.aar",
          "url": "browser-1.3.0.aar",
          "size": 208400,
          "sha512": "714d151cfe8b6dc5f275d7b0dd5f441d222d60b4f08ff2d9cba084e73234b4cb9b21c9027b7fae7ee549d928fd94195f54c3c06a481bde6275932df4ac5197cd",
          "sha256": "e740b1beeac82303415d68bee9d5c1f259716f560a829ca07c7ce97e60850e1b",
          "sha1": "407e57282abe6db9107965a729203210b9a6821b",
          "md5": "f4bd0b4782e1a25c4c3fae304aa982c2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.3.0.aar",
          "url": "browser-1.3.0.aar",
          "size": 208400,
          "sha512": "714d151cfe8b6dc5f275d7b0dd5f441d222d60b4f08ff2d9cba084e73234b4cb9b21c9027b7fae7ee549d928fd94195f54c3c06a481bde6275932df4ac5197cd",
          "sha256": "e740b1beeac82303415d68bee9d5c1f259716f560a829ca07c7ce97e60850e1b",
          "sha1": "407e57282abe6db9107965a729203210b9a6821b",
          "md5": "f4bd0b4782e1a25c4c3fae304aa982c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "browser-1.3.0-sources.jar",
          "url": "browser-1.3.0-sources.jar",
          "size": 96461,
          "sha512": "ef04f4e2db6a70c4afc9e9fd30feda7eb43330223e8a147eb594281c367e8ef6aeab294a917564a55bd583a4f376f9bdff6cc54a8cad03176065e012a0c90f99",
          "sha256": "5a6a01a400e187e3b731768f0e62dfc541d23a172f96b835e30cf4358befa949",
          "sha1": "7ad6013ea18d28a089b76a439ee22941f45e6b95",
          "md5": "7e28c0528491b8a57ec6524220620105"
        }
      ]
    }
  ]
}
