{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-database",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-database-8.0.2.aar",
          "url": "firebase-ui-database-8.0.2.aar",
          "size": 37828,
          "sha512": "ff359a1721e26d0b246aaace9799d7f49112b67f021b77899c8c8c35188b577b79625e450480c4f613504671364f0316f6600ef038ce6bfcfb353810d97958fc",
          "sha256": "1d955ca5f3da10ebc8e2579da8f73a83c20a1f6fa98d2a08c56dc992dbc71aa1",
          "sha1": "9a2b98cb32b87a6126553e5cfd22c6e2e7956116",
          "md5": "3c4e47db0d6defe50d77e1e7ced20a02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-database-8.0.2.aar",
          "url": "firebase-ui-database-8.0.2.aar",
          "size": 37828,
          "sha512": "ff359a1721e26d0b246aaace9799d7f49112b67f021b77899c8c8c35188b577b79625e450480c4f613504671364f0316f6600ef038ce6bfcfb353810d97958fc",
          "sha256": "1d955ca5f3da10ebc8e2579da8f73a83c20a1f6fa98d2a08c56dc992dbc71aa1",
          "sha1": "9a2b98cb32b87a6126553e5cfd22c6e2e7956116",
          "md5": "3c4e47db0d6defe50d77e1e7ced20a02"
        }
      ]
    }
  ]
}
