{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-common",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-common-8.0.2.aar",
          "url": "firebase-ui-common-8.0.2.aar",
          "size": 6785,
          "sha512": "1979972ee508086d3cc4312e3f09a1776f05805f0e586afd90bdac4d38a75ae7df1a2abb174d760ac4d8fe1d7115a4c4d6125d12c97968461228f8a4cb233fa6",
          "sha256": "7a340544e7f2f320ab735877ca7cb0222b8baa2e95adb098c948363dca02f2e2",
          "sha1": "dbd888bf350754d4f7eb7467e708631ca9f47b3b",
          "md5": "e33bea72b736aaab6b1ca1bc822243cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-common-8.0.2.aar",
          "url": "firebase-ui-common-8.0.2.aar",
          "size": 6785,
          "sha512": "1979972ee508086d3cc4312e3f09a1776f05805f0e586afd90bdac4d38a75ae7df1a2abb174d760ac4d8fe1d7115a4c4d6125d12c97968461228f8a4cb233fa6",
          "sha256": "7a340544e7f2f320ab735877ca7cb0222b8baa2e95adb098c948363dca02f2e2",
          "sha1": "dbd888bf350754d4f7eb7467e708631ca9f47b3b",
          "md5": "e33bea72b736aaab6b1ca1bc822243cc"
        }
      ]
    }
  ]
}
