{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7318172"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0.jar",
          "url": "paging-common-3.0.0.jar",
          "size": 758523,
          "sha512": "67f55d211b57a0b0bdf584bddacc0adeef277dd3081afc6dee1bcede1b89f83768ab6e33e30f117c7aeb5e2d6d7f364a451081a027884c07e9a4a12a5184e519",
          "sha256": "2e934ca502ec1311197e7bf0bf0fc37d1384244bfe49932da02773207ec18d79",
          "sha1": "a4aa6ffbc719e85d264dbb0c8d03795fba978729",
          "md5": "57ce5094372e37f2384e35a770bf4995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.0.0.jar",
          "url": "paging-common-3.0.0.jar",
          "size": 758523,
          "sha512": "67f55d211b57a0b0bdf584bddacc0adeef277dd3081afc6dee1bcede1b89f83768ab6e33e30f117c7aeb5e2d6d7f364a451081a027884c07e9a4a12a5184e519",
          "sha256": "2e934ca502ec1311197e7bf0bf0fc37d1384244bfe49932da02773207ec18d79",
          "sha1": "a4aa6ffbc719e85d264dbb0c8d03795fba978729",
          "md5": "57ce5094372e37f2384e35a770bf4995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.0.0-sources.jar",
          "url": "paging-common-3.0.0-sources.jar",
          "size": 139989,
          "sha512": "96b93023bb2ce452dba50bdbc18ca7dfc2270cc8579432caf3406d15718efb290d77dc85987976d63385634b21009d29547553717b0bff79a11b2a8aa14ae934",
          "sha256": "271cd91298439ede3bddd2176f1105b58154a2907638188002acf059dc19fc26",
          "sha1": "305fc4a31769467b3e3872e6970fe9cdc101b400",
          "md5": "0569ded03c6bedf6588dcebf5fbe712f"
        }
      ]
    }
  ]
}
