{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-auth",
    "version": "8.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-auth-8.0.2.aar",
          "url": "firebase-ui-auth-8.0.2.aar",
          "size": 614352,
          "sha512": "5c686f4aaf11b55bda19926b0df9f140cf3ba15ada86f81ebb7958fbafcb7a85dfd26de448b21a0db9260755b8173944bb4daabf836087fc4b6b6365f3fc6776",
          "sha256": "47903686f5042726dd60cd43dc3e197b0d3c3926a94cf131dc32ce23ecd8f5e3",
          "sha1": "d1bf1e3c3e8d447584a38054815655a28c5a32fe",
          "md5": "03729eac0260bf8d4e8ef9b89e528952"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.2.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth"
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-auth-8.0.2.aar",
          "url": "firebase-ui-auth-8.0.2.aar",
          "size": 614352,
          "sha512": "5c686f4aaf11b55bda19926b0df9f140cf3ba15ada86f81ebb7958fbafcb7a85dfd26de448b21a0db9260755b8173944bb4daabf836087fc4b6b6365f3fc6776",
          "sha256": "47903686f5042726dd60cd43dc3e197b0d3c3926a94cf131dc32ce23ecd8f5e3",
          "sha1": "d1bf1e3c3e8d447584a38054815655a28c5a32fe",
          "md5": "03729eac0260bf8d4e8ef9b89e528952"
        }
      ]
    }
  ]
}
