{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-rxjava3",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7318172"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.0.0.aar",
          "url": "paging-rxjava3-3.0.0.aar",
          "size": 18608,
          "sha512": "8f2d96ebce16d599eaf3d330f6b8fa270ee9588bbba1b92c04de51088e614746c5b461568e9b24b8c49c0ea4fa812b1096684955db281c70272f80083dd46fde",
          "sha256": "d75a4059dee9409a8dc7cfcbdf1b45a8f133a7c89ceab39234277c9b1aba62fb",
          "sha1": "7cebd74782b957447c89a09666a64f0dc854776c",
          "md5": "b12ecd9d876c5c221b8e66c4d6753647"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.0.0.aar",
          "url": "paging-rxjava3-3.0.0.aar",
          "size": 18608,
          "sha512": "8f2d96ebce16d599eaf3d330f6b8fa270ee9588bbba1b92c04de51088e614746c5b461568e9b24b8c49c0ea4fa812b1096684955db281c70272f80083dd46fde",
          "sha256": "d75a4059dee9409a8dc7cfcbdf1b45a8f133a7c89ceab39234277c9b1aba62fb",
          "sha1": "7cebd74782b957447c89a09666a64f0dc854776c",
          "md5": "b12ecd9d876c5c221b8e66c4d6753647"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-rxjava3-3.0.0-sources.jar",
          "url": "paging-rxjava3-3.0.0-sources.jar",
          "size": 6068,
          "sha512": "ae7dc427122cbe4efca5482a8a5779f85fab6fe4c1e5c46407df56f9afaf4a7af1571fa10c52afaa76057acfe59c3bb6c25b89a85059345cc88ef6b65dd44ca3",
          "sha256": "80c6dfa53d9f82215ec563802ea1e2774bf789e5b57d2fcb37fd9dc8f27c3a67",
          "sha1": "fd1469b1518a12a94de37c5b793050f37a37ec74",
          "md5": "239218540233dc417395a88b93777830"
        }
      ]
    }
  ]
}
